### ISSUE TITLE
To much redirects if slug changed back to the first slug before the change

### ISSUE THREAD

**Issue by kanow** [wazum/sluggi#1]
Hi, I tried your extension to update slug fields after changing the page title. Your extension also creates redirects after changing the slug. If I change the slug back to the title which was before then a new redirect will be created and those will end in an neverending redirect on that page.

Explanation:

1. page title: "page-a" -> change to "page-b" after saving the new slug, a redirect will be created from page-a to page-b
2. page title: "page-b" -> change to "page-a" after saving the slug, a second redirect will be created. 

I'm using master branch with composer.

**Comment by wazum** [comment]
Good catch @kanow, thanks, this is all too new and I'm still discussing things with colleagues on how to handle the redirects. I'm working on it, but I'm not quiet finished or satisfied myself. That's the reason this stuff is still only in master and not in a new release. Please be a little patient with me ;-) or come up with some ideas (highly appreciated!).

**Comment by wazum** [comment]
Should be fixed in master

**Comment by wazum** [comment]
@kanow a new release is available via packagist and in TER

**Comment by kanow** [comment]
Fine, thanks. I will try the new version after my holiday in two or there weeks :-).

> Please be a little patient with me 

Yes of course ;-)
