### ISSUE TITLE
URL with double slash

### ISSUE THREAD

**Issue by hirnschmalz** [wazum/sluggi#10]
If there is, for some stupid reason, a slug on the start page e.g. `/my-startpage` all the subpage have this part in the slug field.

If the slug of the startpage is changed to (the correct) `/` the slug of the subpages start with `//`.

**Comment by wazum** [comment]
Thanks for your report @hirnschmalz 
I'll asap test and resolve this problem.

**Comment by wazum** [comment]
I could not really reproduce your problem @hirnschmalz, the sub pages had always only one leading slash for every test scenario.
But non the less I fixed some problematic lines with trailing slashes.
So please test with current `master` and report back, thanks in advance!

**Comment by hirnschmalz** [comment]
Hi @wazum ,

that was quick :wink: :+1: .  
Works like charm now.
