### ISSUE TITLE
Unable to save folder with exclude_page_types=254 (folder) 

### ISSUE THREAD

**Issue by christophlehmann** [wazum/sluggi#103]
in TYPO3 12.4.8 with sluggi 12.0.2 I get an Exception when i save a folder
<img width="1120" alt="Bildschirmfoto 2023-11-21 um 22 21 40" src="https://github.com/wazum/sluggi/assets/4953689/ec83a0f7-372e-44ee-bf16-9af6e49394a6">

When i remove `254` from `exclude_page_types` setting, then I don't get the exception.

The function in `typo3/cms-redirects` looks like this
<img width="1076" alt="Bildschirmfoto 2023-11-21 um 22 26 32" src="https://github.com/wazum/sluggi/assets/4953689/e9dd0bb6-fb7b-4aec-b4b0-b85d8562ae55">

Little possibly bad smell here:`$persistedChangedItem` might be null, but in line 88 this is not checked.

**Comment by christophlehmann** [comment]
The same Exception occurs, when one de/activates a page via context menu of page tree

**Comment by wazum** [comment]
Thank you for the report.
I can reproduce it with this latest version of TYPO3 CMS (it works with earlier versions).
I need to take a look at how to solve this.

**Comment by christophlehmann** [comment]
It does not occur any more with todays release TYPO3 v12.4.9. 
Might be that [commit](https://github.com/typo3/typo3/commit/40cbfe18ee) which fixed it.

**Comment by devtroll** [comment]
Fix for TYPO3 v11?
