### ISSUE TITLE
Workspaces error Call to a member function withChanged() on null

### ISSUE THREAD

**Issue by supercaccia** [wazum/sluggi#106]
With TYPO3 v12 and sluggi 12.0.2, if you are into a **workspaces**, if you "edit and save" one page the following error appears:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function withChanged() on null | Error thrown in file www\bp12\typo3\sysext\redirects\Classes\Hooks\DataHandlerSlugUpdateHook.php in line 88. Requested URL: http://bp12:8080/typo3/record/edit?token=--AnonymizedToken--&returnUrl=%2Ftypo3%2Fmodule%2Fweb%2Flayout%3Ftoken%3D--AnonymizedToken--%26id%3D1&edit%5Bpages%5D%5B1%5D=edit `

**Comment by wazum** [comment]
Thanks, already reported here #103
