### ISSUE TITLE
ext:redirect should be dependency

### ISSUE THREAD

**Issue by t3brightside** [wazum/sluggi#11]
Hey,
this ext should be part of core features for sure! Good work! Thanks!

Could be a good idea to make ext: redirects mandatory as Sluggi doesn't work without it.

**Comment by wazum** [comment]
Thanks for the hint,
I'll add it to ext_emconf too, it's already a dependency in composer.json.
The plan is to remove the dependency in the long run, as long as the feature is not explicitly required.

**Comment by wazum** [comment]
Done
