### ISSUE TITLE
Compatibility for TYPO3 v13

### ISSUE THREAD

**Issue by peter-neumann-dev** [wazum/sluggi#111]
We would love to have and also test Sluggi in TYPO3 v13 ♥️🙏🏻

**Comment by vb-benjamin-eyring** [comment]
Agree - do you need help with updating? I could ask if we can sponsor dev-time. 

thx, Benjamin

**Comment by devtroll** [comment]
Any news on this?

**Comment by joey-bolts** [comment]
+1 - Would like to know if this will be updated

**Comment by wazum** [comment]
Yes, there's already a working fork from my colleague Richard:
https://github.com/richardkrikler/sluggi
We'll review and merge next week.

**Comment by wazum** [comment]
Tagged version 13.0.0

**Comment by vb-benjamin-eyring** [comment]
Thank you very much :-)!

**Comment by rafu1987** [comment]
Can you also update TER please? Thank you! :-)
