### ISSUE TITLE
Dependency to sysext redirects

### ISSUE THREAD

**Issue by Schwuuuuup** [wazum/sluggi#12]
Hi,
sluggi seems to depend on the system extension "redirects" to do it's job but this is not stated in the ext_emconf.php not even as "suggest".
On Installations without "redirects" activated (e.g. after an update from 8.7) the missing DB columns lead to errors like "missing table source_host in where clause" 

Regards
Thomas Moll

**Comment by wazum** [comment]
Thanks @Schwuuuuup  for your feedback! This has already been fixed in master for some time, but I now made the extension `redirects` completely optional.
Please test with the latest `dev-master` and report back if it works for you now! :-) 
Aferwards I'll tag a new release and push it on TER.

**Comment by Schwuuuuup** [comment]
Thank you very much for that quick reply!

Seems to work, with no "redirects" activated and with missing redirects-tables the new sluggi doesn't throw errors anymore...
Unfortunately I cannot fully test sluggi in my development environment, and production is still on 8.

I installed sluggi in the hope it would give me a button that recalculates ALL slugs on ALL the pages (of a subtree or something) DISCARDING everything that is currently stored in the slug-fields with a single press. If there is such a button I did not find it. Can you give me a hint?

**Comment by wazum** [comment]
There's another extension for this: https://extensions.typo3.org/extension/ig_slug/
hth, closing this issue, thanks
