### ISSUE TITLE
Redirect to pages with suffix

### ISSUE THREAD

**Issue by stephanederer** [wazum/sluggi#14]
If suffix on site configuration is configured, e.g.
`routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /index.html`
Pages can be called via '/path/' or alternative via '/path/index.html'.

When moving page or changing slug, sluggy doesn't generate a redirect to page with suffix, this calls won't work anymore.

**Comment by wazum** [comment]
@stephanederer ah, ok, didn't know this feature. I'll take a look at it next week.

**Comment by wazum** [comment]
@stephanederer please test with the latest dev-master

**Comment by stephanederer** [comment]
@wazum The fix works on my installation
