### ISSUE TITLE
Deactivate updating slug of current page

### ISSUE THREAD

**Issue by stephanederer** [wazum/sluggi#16]
It's not possible to deactivate updating slug of current page when moving or renaming.

- it's possible to deactivate updating slug **recursively** when **moving page**. But it's not possible to deactivate udating slug of current page.
- it's possible to deactivate updating slug **recursively** when **renaming page**. But if you rename pagetitle and set focus back to the title field it udates the slug of current page (via JavaScript).

**Comment by wazum** [comment]
@stephanederer nice catch, I think it would work if I put this in the lock feature. When the lock for a page is active, it would also affect any move (or other) operation. How does that sound?

**Comment by stephanederer** [comment]
@wazum sounds good, thanks a lot!

**Comment by wazum** [comment]
@stephanederer Please test again with the latest version. Locked pages should now be excluded from any updates.
