### ISSUE TITLE
Slug field is locked although switch says it isn't

### ISSUE THREAD

**Issue by Schwuuuuup** [wazum/sluggi#20]
There is still one minor issue:

Tested on  Vivaldi, Chrome and Firefox (on Linux Mint) and with Version 1.8.3 from TER and 1.9.1 from git: 
![sluggi-lock](https://user-images.githubusercontent.com/16288510/74839513-ad067b80-5325-11ea-8e2e-a85d96359d14.png)

As you can see there is no edit button, although the lock is not engaged. 
"Have you tried turning it on and off again?" unlocks the field successfully though.

you can sometimes see the edit button for a fraction of a second before it vanishes after loading the backend page.

**Comment by wazum** [comment]
@Schwuuuuup  this is actually meant to be a feature. If the _Synchronisiere URL Segment_ switch is active, you shouldn't edit the slug, so the buttons are removed. If you switch that off, you get the default recalculate and edit buttons.

**Comment by wazum** [comment]
(I see, I still have an old screenshot in the README too …)

**Comment by Schwuuuuup** [comment]
Ah, I see.
sorry I did not get, that the _Synchronisiere URL Segment_ switch is meant to lock the input field as well.
No problem then.
