### ISSUE TITLE
Create redirects without endtime

### ISSUE THREAD

**Issue by dahaupt** [wazum/sluggi#21]
It would be great to skip adding an `endtime` on redirect records in case the extension setting `redirect_lifetime` is empty.

Currently, there is always an `endtime` set with
```
'endtime' => $redirectLifetime !== false ? $redirectLifetime : strtotime('+1 month')
```
inside `DatamapHook.php`.

**Comment by wazum** [comment]
is fixed in 1.9.5, thanks for the suggestion
