### ISSUE TITLE
Wrong redirect generated for sites with URL prefix

### ISSUE THREAD

**Issue by maechler** [wazum/sluggi#22]
I have tested this with TYPO3 `9.5.14` and sluggi `1.9.1`.  It can be reproduced by adding a site configuration with a full URL prefix, e.g. `/en/`.

If you create a page named `example` and then rename it to `example new`, `sluggi` will create a regular redirect and a variant:

`/en/example -> /en/example-new`
 
`/en/example/en -> /en/example-new`

There are two problems to this, first `/en/` gets recognised as variant, second the variant is always appended to the URL although it should be prepended in that case. I am not entirely sure what the best way would be to solve that issue..

The following screenshot shows the problem in the debugger:

![image](https://user-images.githubusercontent.com/4113819/78109012-b42aaa00-73f8-11ea-92c0-8d0cf84477fd.png)

**Comment by maechler** [comment]
We added the following check before `if ($currentSlug !== $slug) {` in order to workaround the issue.  

```php
if ($variant === $sitePath) {
    $variant = null;
}
```

If you think this is ok, I would be happy to prepare a pull request. If you have a better way to solve that issue, please let me know!

**Comment by wazum** [comment]
Thankx, I'll take a look at it in the next couple of days

**Comment by wazum** [comment]
@maechler is fixed in 1.9.5, thanks for the solution
