### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by rafu1987** [wazum/sluggi#26]
Hey there,

thanks for your work with sluggi. :-)

Will you add TYPO3 10 compatibility. I know they introduced the automatic updates for URL segments and redirects, but still, sluggi provides some nice additional features. :-)

**Comment by wazum** [comment]
Sure, I thought about it and actually working on it, but will take some time.

**Comment by rafu1987** [comment]
Hi :-)
Just wanted to ask, if there's any update on a TYPO3 10 integration / support. If you need any help for testing, etc. I would gladly help out!

**Comment by djcprinse** [comment]
Hi. Just wanted to ask if there is any update yet on a TYPO3 v10 compatible version or if you have an estimated time for the update to become available? If you need help with testing, let me know!

**Comment by wazum** [comment]
We soon start with the first large TYPO3 10 upgrades in our company, so there is enough reason for me to finish the extension for 10.
There's a fork https://github.com/GaryWilsonJr/sluggi that should at least work without errors, but I'm not sure, all features still work.

**Comment by djcprinse** [comment]
Thank you for the quick reply :) I'll have a look if the fork is working for our use case.

**Comment by wazum** [comment]
@djcprinse @rafu1987 @GaryWilsonJr 
Hey guys, check out the completely rewritten version for 10: https://github.com/wazum/sluggi/tree/typo3-10
and give feedback, thanks!

**Comment by mariekesdb** [comment]
@wazum just tested it. I found a bug in the SlugHelper fetchOne() method isn't found.
I think it should just be fetch() 

Can I just put this here or should I make another issue for this?

**Comment by wazum** [comment]
Thanks @mariekesdb 
my colleagues updated the Doctrine version in the project I used to upgrade the extension … 
TYPO3 CMS depends on an older version, I'll fix it asap

**Comment by wazum** [comment]
@mariekesdb I updated the branch, thanks again

**Comment by mariekesdb** [comment]
@wazum thanks again for the fast fix

**Comment by wazum** [comment]
Tagged new version for 10 as `2.0.0`
