### ISSUE TITLE
Bug in Slug access restrictions for /

### ISSUE THREAD

**Issue by datango** [wazum/sluggi#27]
Hi,

thank you, for building the sluggi extension. It is realy usefull.

The problem: 

/
demo    Access group DEMO
 test    Access group Test
   page1  Access group Test
   
This results in 

[https://servername.de/demo]/test/page1

[] = Fixed part - can not be changed

That is correct. The user has no access to demo. So it can not be changed.

Slug on the test page 

[https://servername.de/demo]/test/page1

Also correct.

But if the user is in the demo group and has no access (no mount) to / he gets:
[https://servername.de]/demo/test/page1

So the user can edit the slug and access the / namespace.

What i was expecting:
[https://servername.de/demo]/test/page1

Also locking the slug of the page demo1 does not block the subpages for editing the hole url path.

**Comment by wazum** [comment]
@datango  If the user has access to /demo he can change that anytime to /something-else (root level), so I see no bug here. 
As for the locking … that would be a bit complicated to incorporate into the slug building, as you can lock pages anywhere in the hierarchy. 
Would you disallow changing the slug segments up to the nearest locked page here?
I will think about that though …

**Comment by wazum** [comment]
No further feedback, closed
