### ISSUE TITLE
Exception when creating new page

### ISSUE THREAD

**Issue by mgur** [wazum/sluggi#3]
There is a bug on creating new page (if permissions on subpart of pagetree).
It's not possible to add new pages.

**Comment by wazum** [comment]
@mgur  can you elaborate on this? This is not really a helpful ticket.
What did you do and what happened? Provide some screenshots, etc. Thanks!

**Comment by wazum** [comment]
A better problem description or any hints on this @mgur ?

**Comment by moe2k** [comment]
I have the same problem:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to Wazum\Sluggi\Helper\PermissionHelper::getTopmostAccessiblePage() must be of the type integer, string given, called in 

/public/typo3conf/ext/sluggi/Classes/Backend/Hook/DatamapHook.php on line 37 \| TypeError thrown in file 

public/typo3conf/ext/sluggi/Classes/Helper/PermissionHelper.php in line 66.

**Comment by wazum** [comment]
Thanks @moe2k for the details. Now it's clear, that this is fixed already for some time in master.
I released a new version (1.2.0) right now in TER and on packagist.
Please update and give feedback if everything's working for you. tia
