### ISSUE TITLE
Redirects: missing option for Keep GET Parameters

### ISSUE THREAD

**Issue by danielakeil** [wazum/sluggi#31]
Great module by the way. The only thing I am missing in the extension settings is an option for the redirects to keep the GET parameters. It is important to keep this information fro tracking purpose when redirecting a page. 
Thank you for creating this module

**Comment by wazum** [comment]
@danielakeil  the new options are available with version > 1.10.0 hth

**Comment by danielakeil** [comment]
Perfekt, thank you @wazum
