### ISSUE TITLE
getPrefix() has been removed in v10

### ISSUE THREAD

**Issue by valentin-** [wazum/sluggi#34]
Hi, looks like the getPrefix-method inside the permission check has been removed in Typo3 v10 in `\TYPO3\CMS\Backend\Form\Element\InputSlugElement.`

https://github.com/wazum/sluggi/blob/master/Classes/Backend/Form/InputSlugElement.php#L50

It's working for me to simple insert the code snippet from v9 in `Wazum\Sluggi\Backend\Form\InputSlugElement`

```/**
     * Render the prefix for the input field.
     *
     * @param SiteInterface $site
     * @param int $requestLanguageId
     * @return string
     */
    protected function getPrefix(SiteInterface $site, int $requestLanguageId = 0): string
    {
        $language = ($requestLanguageId < 0) ? $site->getDefaultLanguage() : $site->getLanguageById($requestLanguageId);
        $base = $language->getBase();
        $baseUrl = (string)$base;
        $baseUrl = rtrim($baseUrl, '/');
        if (!empty($baseUrl) && empty($base->getScheme()) && $base->getHost() !== '') {
            $baseUrl = 'http:' . $baseUrl;
        }
        return $baseUrl;
    }
```

**Comment by wazum** [comment]
@valentin- thanks for your report, sluggi is not (yet) ready for version 10

**Comment by wazum** [comment]
@valentin-  Hey, check out the completely rewritten version for 10: https://github.com/wazum/sluggi/tree/typo3-10
