### ISSUE TITLE
New pages created by an non-admin gets wrong slug

### ISSUE THREAD

**Issue by mariekesdb** [wazum/sluggi#39]
When a non-admin creates a new page by right-clicking an existing page and choosing new, so not via the page-drop-wizard, and the setting last_segment_only is activated the page gets the wrong slug. Saving the page again after the first generation fixes the slug.

How to reproduce:
- In the extension configuration set basic.last_segment_only to true
- Change to a non-admin user
- As the non-admin user create a new page by right-clicking an existing page and choosing new
- save the page
- the slug is now [base-url] / [number] which is wrong
- save the page again, the slug gets fixed

Expected behaviour:
- The slug is being generated correctly the first time saving

Sluggi 1.10.1 and TYPO3 9.5.22, also tested it with the CMS10 version from https://github.com/GaryWilsonJr/sluggi and there it has the same problem

**Comment by wazum** [comment]
@mariekesdb thanks for reporting this issue

**Comment by wazum** [comment]
@mariekesdb Should be fixed in 1.10.2 (TYPO3 CMS 9) and in the typo3-10 branch
(please don't use the fork, use the rewrite for TYPO3 10 (see branch for now, as we currently test before the first release))

**Comment by mariekesdb** [comment]
@wazum wow that's fast, thanks a lot for fixing this!

I was just testing the CMS 10 branch and found one issue which I reported here https://github.com/wazum/sluggi/issues/26

**Comment by mariekesdb** [comment]
The bug is fixed so i will close this ticket
