### ISSUE TITLE
Configuration Options missing when installed in Typo3 Version 9.5.8

### ISSUE THREAD

**Issue by maniac555** [wazum/sluggi#4]
Hi, when I install the extension with Typo3 Version 9.5.8 I only get the one configuration option. See screenshot. Renaming slug segements recursively is not working. Maybe because the config is not present? Or is there anything I'm missing? I dowloaded the latest version of your ext from TER.

![2019-07-16 13_33_10-sluggi-config-options](https://user-images.githubusercontent.com/40887315/61291380-ad0e2e00-a7ce-11e9-83d0-dcd10500b166.png)

Thanks for checking!

**Comment by wazum** [comment]
Hi @maniac555 thanks for asking,
the latest features are only available in master.
I'll tag a new release soon though … so please use the github code for now

**Comment by wazum** [comment]
@maniac555 a new release is available via packagist and in TER
