### ISSUE TITLE
Renaming a page in pagetree (double click) does not update the slug

### ISSUE THREAD

**Issue by christophlehmann** [wazum/sluggi#40]
When i rename a page via page tree and have tx_sluggi_sync enabled, the slug is not updated.

**Comment by wazum** [comment]
@christophlehmann Thanks for reporting this issue, which version are you using (for TYPO3 CMS 9 or 10)?

**Comment by christophlehmann** [comment]
We use 10.4.10

**Comment by wazum** [comment]
@christophlehmann  please test with the latest `dev-master` if this resolves your issue

**Comment by christophlehmann** [comment]
It works perfect. Thanks for your investigation!
