### ISSUE TITLE
Redirect to self is created in multilanguage site

### ISSUE THREAD

**Issue by mariekesdb** [wazum/sluggi#44]
When you have a multilanguage site and edit a page in the default language, a redirect is created from the second language page to itself.

For example: 
- "page 1" exists in language 0 and 1 with slugs site.com/page and site.com/en/page
- edit a property of the default page in the backend, e.g. the author. 
- when you save the page a redirect is created from site.com/en/page to site.com/en/page

I use TYPO3 10.4.12 and this problem is in the dev-master version of the exention and it's created with the fix for issue https://github.com/wazum/sluggi/issues/40 because in version 2.0.0 the issue isn't there

**Comment by wazum** [comment]
@mariekesdb  I'll take a look at it tomorrow
