### ISSUE TITLE
Error "Too few arguments to function Wazum\Sluggi\Backend\Hook\DataHandlerSlugUpdateHook"

### ISSUE THREAD

**Issue by cseifert** [wazum/sluggi#55]
Hi folks,

I'm using TYPO3 9 LTS and the latest 2.0.2 version of sluggi. When I open the backend and try to edit a backend user record, the following error occurs when saving the updated record: "Too few arguments to function Wazum\Sluggi\Backend\Hook\DataHandlerSlugUpdateHook"

Downgrading the version to 2.0.0 fixed the error so that it doesn't occur. Upgrading to 2.01. or later, the exception is thrown again.

I hope it helps to reproduce the situation.

Best regards,
Christian

**Comment by wazum** [comment]
@cseifert  version >= 2 is for TYPO3 CMS 10, as you can see in composer.json and ext_emconf: https://github.com/wazum/sluggi/blob/2.0.2/composer.json
Use the latest update 1.11.0 for TYPO3 CMS 9.
