### ISSUE TITLE
Allow option to choose between nested array and simple array in generatorOptions:fields

### ISSUE THREAD

**Issue by sebastiande** [wazum/sluggi#58]
Setting the pages_fields to a value "nav_title,title" results in a nested array.

The default behavior of Typo3, in this case, is taking nav_title, and only if this is empty use title:
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Slug/Properties/GeneratorOptions.html

I would assume that it is not set as a nested array but as a normal array, resulting in taking both fields into account.

Is it possible to have an option to control this behavior or at least make it transparent to write the string as array already "['nav_title','title]" ?

If we leave the field empty and set the configuration on our own there is an exception happening.

Thanks,
Sebastian

**Comment by wazum** [comment]
@sebastiande nice catch, seems like this has changed eventually.
I'll take a look at it.

**Comment by sebastiande** [comment]
Thank you!
