### ISSUE TITLE
version 2 breaks sys_file_reference when copying pages in TYPO3 backend

### ISSUE THREAD

**Issue by Kephson** [wazum/sluggi#63]
Hello,
we have a TYPO3 Version 9.5.27 with following configuration:
- TYPO3 9.5.27
- 11 Languages configured
- use the pages->media field to add images for the pages

When copying pages with existing translations, it breaks with an error message and the default language has doubled sys_file_references in media field.
After removing sluggi the problem has gone.

I will provide a detailed description how to recover this behaviour in a fresh installation and provide a site package to test it.

**Comment by wazum** [comment]
Version 2 is not compatible with TYPO3 9, as you can see in composer.json and in the documentation (first sentence).

**Comment by Kephson** [comment]
Sorry, this was a mistake, we're using version 1.11.0 from packagist.
