### ISSUE TITLE
TYPO3 11.5 support

### ISSUE THREAD

**Issue by rafu1987** [wazum/sluggi#66]
Hey,
Is support for TYPO3 11.5 planned? This would be awesome! 🙂

**Comment by TBschen** [comment]
I sure hope so, I won't even think about using 11.5 without sluggi :)

I still don't understand why slugs were implemented the way they are in TYPO3.
Slug syncing with title, optional slug lock, hyphens instead of forward slashes, ... sluggi is the way to go!

**Comment by wazum** [comment]
I'm already working on it …

**Comment by supercaccia** [comment]
Don't forget the support for workspaces ;) https://github.com/wazum/sluggi/pull/56

**Comment by rafu1987** [comment]
@wazum do you maybe have a timeframe, when an updated version for TYPO3 11 will be available? Do you need help? There is also a pull request available already (https://github.com/wazum/sluggi/pull/68). :-) Would be great, thanks!

**Comment by wazum** [comment]
I'm currently finishing the complete rework for TYPO3 CMS 11 in branch feature/typo3-11 (WIP),
expect a new tag this week.

**Comment by rafu1987** [comment]
Thanks a lot for updating sluggi for TYPO3 11. I saw that the extension is already updated on Packagist. Could you also upload the new version to TER? That would be awesome, thanks! 🙂

**Comment by wazum** [comment]
@rafu1987 done
