### ISSUE TITLE
Versions 2.1.2 and 2.1.3 are broken

### ISSUE THREAD

**Issue by eliashaeussler** [wazum/sluggi#69]
I just updated EXT:sluggi from 2.1.1 to 2.1.3 and got an exception during TCA migration (e.g. when clearing caches or performing DB schema update):

> [ UnexpectedValueException ]                                            
> Missing "type" in TCA of field "['pages']['[["nav_title"']['config']".

I have the following extension configuration:

```php
'sluggi' => [
    'last_segment_only' => '0',
    'pages_fields' => '[["nav_title","title"]]',
    'slash_replacement' => '1',
    'synchronize' => '1',
    'whitelist' => '',
],
```

After a short research I was able to track it down to the following:

It seems like 02f363c7fa9117d911230712775a5362759f0a55 is no longer available in versions 2.1.2 and 2.1.3, see for example https://github.com/wazum/sluggi/blob/2.1.2/ext_conf_template.txt#L6. Said commit was not merged back into the v2 compatibility branch `typo3-10` which you likely used to create both versions.

This probably affects more changes that were introduced with 2.1.0 and 2.1.1 which might now be missing in the 2.1.2 and 2.1.3 versions, but haven't checked on this further.

**Comment by wazum** [comment]
@eliashaeussler thanks, I'll take a look at what happened there 😖

**Comment by wazum** [comment]
@eliashaeussler  don't know what I did there, oh my 😮
can you test with the recent typo3-10 branch? If everything works out, I'll tag a new version 2.1.4.
I have already removed the broken tags.

**Comment by eliashaeussler** [comment]
@wazum Thanks for taking care, it works for me :)

**Comment by eliashaeussler** [comment]
Hi @wazum, do you already have a schedule for the 2.1.4 release? 🙂

**Comment by wazum** [comment]
Pushed a new 2.2.0 with several other fixes

**Comment by eliashaeussler** [comment]
Thank you 🎉

**Comment by TBschen** [comment]
Would you consider uploading 2.2.0 to the typo3 repository? For those still on typo3 10, the broken version 2.1.3 is still the most recent upload there.

**Comment by wazum** [comment]
Done
