### ISSUE TITLE
Redirect has wrong domain when changing translated page title

### ISSUE THREAD

**Issue by FamousWolf** [wazum/sluggi#70]
TYPO3 version: 10.4.26
sluggi version: 2.2

If you have a multi language site where each language has a different domain, the redirects that are created when changing a translated page always has the domain for the main language.

For example:

The main language is English and has the domain `example.com`. The site also has the language Dutch, with the domain `example.nl`. If I change the title for a Dutch page translation, the redirect that is created is for the domain `example.com`.

**Comment by FamousWolf** [comment]
I see this isn't a problem anymore in the current master, as the bug is in Classes/Backend/Service/SlugService.php and this has been cleaned up in master. However, this is a bug in the version for TYPO3 10.

**Comment by wazum** [comment]
Merged, thanks
