### ISSUE TITLE
Redirect has wrong language-suffix

### ISSUE THREAD

**Issue by borisw1** [wazum/sluggi#75]
TYPO3 10.4.28
sluggi: 2.1.3
When creating a new redirect in foreign languages it takes the suffix to the end.
F. e.:  /en/global/welcome-center/preparing.html -> /en/global/welcome-center/preparing-new/en.html

**Comment by wazum** [comment]
Give me some more hints about your site configuration and setup, thanks.
And use the latest version for TYPO3 10: 2.2.0 for tests.

**Comment by borisw1** [comment]
with version 2.2.0 no problems anymore. Thanks
