### ISSUE TITLE
Has issued with PHP 8 / 8.1, but does not exclude it in requirements

### ISSUE THREAD

**Issue by subnoodle** [wazum/sluggi#76]
I hit a bug when working with sluggi and PHP 8.x:
When cut / past a page in the pagetree, an error comes up:
`tx_sluggi_lock not a column... `
(roughly). I counterchecked the database: field is there.
I downgraded to PHP 7.4., works again.
Can you reproduce the bug?
Don't hesitate asking, if something is unclear.
Thx

**Comment by freshworkx** [comment]
I have a similar error with the backend in TYPO3 11 with PHP 8.1:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "tx_sluggi_lock" in /var/www/html/web/typo3conf/ext/sluggi/Classes/Helper/PermissionHelper.php line 44`

I have found the error and made this pull request, pls merge.
