### ISSUE TITLE
Loops are created

### ISSUE THREAD

**Issue by MediKathi** [wazum/sluggi#81]
Hello,

it is Possible to create a redicet loop

Steps to reproduce:

- Create a Page with name A
- set the name to B
- change it back to A

This creates 2 redirects this causes the system to Crash
At least in our case with Flux.

After The loop is manually fixed, everthing works fine again.

**Comment by wazum** [comment]
@MediKathi  which TYPO3 and which sluggi version are you using?
The redirects are created by the core (except in the old version for CMS 9, but I won't touch that anymore), please test without sluggi and report if it (surprisingly) works without my extension.

**Comment by MediKathi** [comment]
@wazum I using Typo3 11.5.17 and Sluggi 3.0.2

As you mentioned, I tested the situation without sluggi, but the problem still occurs.

Loops are still genereated if I update the slug from A to B and backagain.

But this is not an issue of slugg :)

**Comment by wazum** [comment]
Thanks for your feedback
