### ISSUE TITLE
Wrong base URL for multi site instances

### ISSUE THREAD

**Issue by hirnschmalz** [wazum/sluggi#89]
I'm using the `v12` Branch with the latest TYPO3 v12 LTS version.

I'm running a multi site instance and if the site root page is saved **and Synchronize URL segment** is activated, a increasing integers is added to the slug field. This does not happen if the feature is disabled and the URL segmented is regnerated wit a click on the refresh icon.

All the site roots are placed as childs of PID 0.

**Comment by wazum** [comment]
@hirnschmalz I'll take a look at it, thanks for the report
