### ISSUE TITLE
Interoperation with extension internetgalerie/ig_slug

### ISSUE THREAD

**Issue by moe2k** [wazum/sluggi#9]
The extension "ig_slug" also offers a "slug lock" feature, the field is called "slug_locked" there. Sluggi's field is  "tx_sluggi_lock". The sluggi lock field is not shown if ig_slug is installed, so both extensions are incompatible to each other. It would actually be nice if both extensions could share the same field since it behaves the same, because ig_slug features a nice backend module which is useful in combination with sluggi. Maybe you could get in touch with each other. I've created an issue there too: https://github.com/internetgalerie/ig_slug/issues/7

**Comment by moe2k** [comment]
My suggestion would be to rename "tx_sluggi_lock" to "slug_locked", because I would expect a "slug lock" to have a global scope and consider it OK to leave out the namespace here.

**Comment by moe2k** [comment]
Another solution could be to make it configurable which field to use.

**Comment by christophlehmann** [comment]
>Another solution could be to make it configurable which field to use.

I would rather unify it and use `slug_locked` as suggested. Making it configurable introduces new code unnecessarily.

**Comment by dkd-kaehm** [comment]
IMHO, it is done and can be closed:
https://github.com/wazum/sluggi/blob/06f900335b11deca6d2e1c3282ba4cf61d03d48c/ext_tables.sql#L4

**Comment by moe2k** [comment]
Thanks a lot! Yes, I consider it closed.

**Comment by moe2k** [comment]
Closed.
