### ISSUE TITLE
EXT:sluggi with TYPO3 v11 and PHP 8.1

### ISSUE THREAD

**Issue by IvayloIvanov** [wazum/sluggi#92]
Hello,

after the version change of the extension according the TYPO3 versions an installation of EXT:sluggi on a system TYPO3 v11 and PHP 8.1 is not possible anymore.

In v3.0.3 the requirements of PHP was "php": ">=7.2.0",
https://github.com/wazum/sluggi/blob/3.0.3/composer.json

In v11 -> "php": "^7.4",
https://github.com/wazum/sluggi/blob/11.0.1/composer.json

Will it be possible to run EXT:sluggi with PHP 8.1 on TYPO3 v11?

Best regards
Ivaylo

**Comment by wazum** [comment]
Thanks for the hint, I'll update the requirements.

**Comment by wazum** [comment]
@IvayloIvanov should be fixed in 11.1.0, please test

**Comment by IvayloIvanov** [comment]
Thank you!
The EXT:sluggi v11.1.0 with PHP 8.1 and TYPO3 v11 worked fine.
