### ISSUE TITLE
Slug editing on restricted pages does not work

### ISSUE THREAD

**Issue by wesscoric** [wazum/sluggi#94]
In our system, most editors have an entry point into the page tree that is controlled by an appropriate user group. However, editors can see the full path in the slug and can also edit it.
Does this feature need to be configured extra or is it not working right now? This is not so tragic now, as it seems to be the normal behavior. But it was one of the reasons why we decided to use "sluggi".
Could you please check here as well.

We use Typo3 11.5.31 and sluggi 11.1.0

Greetings Wesley

![sluggi](https://github.com/wazum/sluggi/assets/145663058/2f3d6f43-aea5-4685-90fd-ea18362de59a)

**Comment by wazum** [comment]
@wesscoric  thanks for the hint, I made a mistake there, it's fixed now and a new version is tagged

**Comment by wesscoric** [comment]
@wazum Thank you very much. Works exactly as expected.
